### ISSUE TITLE
Servers lost pointer to puppet

### ISSUE THREAD

**Issue by shapi78** [graduway/psick#94] opened 2018-10-10 14:03 UTC
Puppet agents lose connection to puppet master
Will try to create record on puppet.conf or in hosts file

**Comment by shapi78** [comment] 2018-10-10 14:36
regenerate puppet.conf on agent

**Comment by shapi78** [comment] 2018-12-18 12:44
Fix certificate of puppetmaster

**Comment by olegy-ait** [comment] 2019-01-03 22:16
It happens because of puppet master certificate does not have all required DNS alternative names. See puppet agent log - [1], also see dev puppet master cert info - [2].
The cert is generated only for 'puppet.dev.us-east-1.graduway.com' but it also should contains 'puppet' alternative DNS [2] (correct cert file example - [3]).

The cert file was generated without alternative names because server variable is not correct in puppet.conf on puppet master [4] and puppet on puppet master was not configured itself properly.
Also due to the same reason puppet was not able to generate correct dns_alt_names [4] (second name should be FQDN but it is 'puppet.').
'server' variable is incorrect (puppet.us-east-1.dev.graduway.com) because it was generated by previoud version of PSICK.

Proposed solutions:
Fix current masters servers:
1. Fix 'server' variable on masters.
2. Run puppet apply on master
3.  Regenerate puppet master cert and other certs with proper alt dns names.

**OR**

The better idea is to delete current master node at all, create it from scratch, check if the cert is generated properly and other dev nodes can connect to it automatically.

**Comment by olegy-ait** [comment] 2019-01-05 09:03
I performed end to end deployment for puppet master node on my AWS account.
The issue is still reproduced.

The root of the problem is in the following line of bootstrap-puppet-master.sh script: 
export FACTER_domain="$domain"

Terraform does not resolve $domain as terraform variable. It should be ${domain}.
More details [1] and [2].
Meantime according to Alessandro it is not actually needed and Puppet resolves domain automatically.
I tested it on my deployment and it creates cert properly event without  FACTER_domain variable.
Also I fixed hostname definition for hosts file. 

Please review and merge PR 91 [3].

1- https://www.terraform.io/docs/providers/template/d/file.html
2- https://www.terraform.io/docs/configuration/interpolation.html
3- https://github.com/graduway/tfcode/pull/91

**Comment by olegy-ait** [comment] 2019-01-08 09:32
The certificate issue is fixed.

Meantime there is a problem with bootstrap-puppet-agent.sh.
It executes "puppet agent --test --server puppet.${domain}" command twice [1].
Exit code after 1st run is 2 [2] and due to 'set -e' for the init script the script does not execute the 'puppet agent' 2nd time.

Need to decide how to avoid this problem. 
1st option - suppress it on bash script level. 
Like "puppet agent --test --server puppet.${domain} || true"

2nd option - probable there is some native PSICK way. (like 'papply.sh' or something else) @alvagante any suggestion?

1- https://github.com/graduway/tfcode/blob/fb5db0262af3bf32cc333706b298665357ddde5a/modules/shared/bootstrap-puppet-agent.sh#L44
2- http://i.imgur.com/dv7xUjS.png

**Comment by alvagante** [comment] 2019-01-08 09:40
Exit code 2 is a valid exit code when a Puppet runs makes changes (wirthout errors).
So, puppet side, it doesn't involve any error.
I'd handle it on the shell script directly, trapping it and preventing the script from exiting early.
See a sample approach on the papply.sh script https://github.com/graduway/psick/blob/production/bin/papply.sh#L32

**Comment by alvagante** [comment] 2019-01-08 09:45
For some more context: the exit code 2 (on successfull puppet runs with changes) is due to the --detailed-exitcodes option of the puppet agent command, which is added when using the -t option.
You may try to skip it by using
puppet agent --onetime --verbose --no-daemonize --no-usecacheonfailure --no-splay --show_diff
instead of puppet agent -t (which includes all the above options + the detailed exit code one)
For more info:
https://puppet.com/docs/puppet/6.1/man/agent.html

**Comment by antgel** [comment] 2019-01-08 12:39
Fixed in https://github.com/graduway/tfcode/pull/92.

**Closed as completed by antgel** 2019-01-08 12:39 UTC
